### ISSUE TITLE
Show trailing whitespace only mode

### ISSUE THREAD

**Issue by spkane** [davidhouchin/whitespace-plus#1]
It would be great to have a mode that would only show trailing whitespace, or whitespace on a line with no text.

**Comment by strikekat** [comment]
I like it. I wonder what would be the best way to change render modes. Could look into a command with parameters, or some kind of configuration for a persistent change.

**Comment by spkane** [comment]
A config would be nice to set the default possibly, and then have commands something like this:

Whitespace+ Enable Trailing
Whitespace+ Enable All
Whitespace+ Disable

**Comment by strikekat** [comment]
I'm sorry about the huge delay (life, work, etc..), but the latest update overhauls the extension and adds a trailing whitespace mode as well as the ability for custom patterns or decorators. If you would still find it handy! You can also change the default through the config file. Check the readme for more details.
#2

**Comment by spkane** [comment]
@davidhouchin No issues. The update looks really good. 

I loaded it up, explored the functionality a bit, switched it to "trailing" mode and then adjusted the trailing config to look like this:

```
{
        "name": "trailing",
        "enabled": false,
        "pattern": "[^\\S\\r\\n]+$",
        "style": {
            "borderWidth": "1px",
            "borderRadius": "2px",
            "borderStyle": "solid",
            "light": {
                "backgroundColor": "rgba(255, 0, 0, 0.3)",
                "borderColor": "rgba(169, 169, 169, 0.4)"
            },
            "dark": {
                "backgroundColor": "rgba(255, 0, 0, 0.3)",
                "borderColor": "rgba(169, 169, 169, 0.4)"
            }
        }
    }
```

and viola, all is good.

Thank you very much for getting this in. It is much appreciated!
