### ISSUE TITLE
Question for `Whitespace+ Toggl` command

### ISSUE THREAD

**Issue by tadashi-aikawa** [davidhouchin/whitespace-plus#3]
Thanks for the great plugin !!
It is more great if I need not to exec `Whitespace+ Toggl` command when I open vscode every time.

Do you have any solutions?

**Comment by strikekat** [comment]
Hi @tadashi-aikawa, I published version 0.0.4 just now, it adds a new "autoStart" property in the configuration that makes the extension start automatically every time you open VSCode.
Just run the Whitespace+ Config command, and change "autoStart" to true. Hope that helps!

**Comment by tadashi-aikawa** [comment]
@davidhouchin 
Thanks for your quick response and version up!
It worked as expected when I change "autoStart" to true.
